# Generated by Django 4.2.3 on 2023-07-13 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('most_annoyed_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('most_annoyed_score', models.FloatField(blank=True, null=True)),
                ('most_disgust_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('most_disgust_score', models.FloatField(blank=True, null=True)),
                ('most_happy_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('most_happy_score', models.FloatField(blank=True, null=True)),
                ('most_fear_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('most_fear_score', models.FloatField(blank=True, null=True)),
                ('most_sad_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('most_sad_score', models.FloatField(blank=True, null=True)),
                ('most_surprise_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('most_surprise_score', models.FloatField(blank=True, null=True)),
                ('most_neutral_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('most_neutral_score', models.FloatField(blank=True, null=True)),
                ('male_most_annoyed_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('male_most_annoyed_score', models.FloatField(blank=True, null=True)),
                ('male_most_disgust_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('male_most_disgust_score', models.FloatField(blank=True, null=True)),
                ('male_most_happy_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('male_most_happy_score', models.FloatField(blank=True, null=True)),
                ('male_most_fear_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('male_most_fear_score', models.FloatField(blank=True, null=True)),
                ('male_most_sad_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('male_most_sad_score', models.FloatField(blank=True, null=True)),
                ('male_most_surprise_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('male_most_surprise_score', models.FloatField(blank=True, null=True)),
                ('male_most_neutral_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('male_most_neutral_score', models.FloatField(blank=True, null=True)),
                ('female_most_annoyed_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('female_most_annoyed_score', models.FloatField(blank=True, null=True)),
                ('female_most_disgust_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('female_most_disgust_score', models.FloatField(blank=True, null=True)),
                ('female_most_happy_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('female_most_happy_score', models.FloatField(blank=True, null=True)),
                ('female_most_fear_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('female_most_fear_score', models.FloatField(blank=True, null=True)),
                ('female_most_sad_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('female_most_sad_score', models.FloatField(blank=True, null=True)),
                ('female_most_surprise_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('female_most_surprise_score', models.FloatField(blank=True, null=True)),
                ('female_most_neutral_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('female_most_neutral_score', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
