# Generated by Django 4.2.3 on 2023-07-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0003_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='chart_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='report',
            name='disgust_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='fear_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='happy_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='neutral_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='sad_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='surprise_count',
            field=models.IntegerField(default=0),
        ),
    ]
