# Generated by Django 4.2.3 on 2023-07-17 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0004_report_chart_image_report_disgust_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='angry_count',
            field=models.IntegerField(default=0),
        ),
    ]
