# Generated by Django 4.2.3 on 2023-07-23 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0007_report_female_most_annoyed_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('DONE', 'DONE'), ('PENDING', 'PENDING')], default='PENDING', max_length=250),
        ),
    ]
