# Generated by Django 4.2.3 on 2023-07-23 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0008_alter_report_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-id']},
        ),
    ]
