# Generated by Django 4.2.3 on 2023-07-23 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0010_report_female_most_annoyed_face_height_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='angry_count',
            new_name='annoyed_count',
        ),
    ]
